### ISSUE TITLE
[Question] Is the dev-server command expected to run for each test suite / spec file?

### ISSUE THREAD

**Issue by aesyondu** [playwright-community/jest-playwright#50]
I have the following jest-playwright.config.js:

```javascript
  server: {
    command: 'npm run test-server',
    port: 4000,
    launchTimeout: 30000,
  },
```

Where test-server is just:

```json
    "server": "bin/rails server",
    "test-server": "RAILS_ENV=test npm run server -- -p 4000",
```

When I execute my tests individually, say `jest -- test/e2e/mytest.spec.js`, It works fine (runs the server, runs the test, closes the server via SIGTERM). However, when I run all tests via `jest`, there is a race condition happening, where before the previous server is terminated, another server is attempting to start, however something somewhere complains:
```
Another process is listening on 4000. Should I kill it for you? On linux, this may require you to enter your password. (Y/n)
```

Which effectively hangs my tests. How do I make it that only one server is run for all tests?

**Comment by aesyondu** [comment]
I found that adding this to the jest-playwright.config.js server property solves my issue. But is there a way to create one server for all test suites, not one server for each test suite?

```javascript
    usedPortAction: 'kill',
```

**Comment by aesyondu** [comment]
In the meantime, the docs provides a way for a global setup / teardown of the server. I just did that instead:

https://github.com/smooth-code/jest-puppeteer/tree/master/packages/jest-dev-server

**Comment by mxschmitt** [comment]
Unfortunately we run separate instances of them for each sub-test. Would be definitely an improvement if we only run it once.

**Comment by thernstig** [comment]
This also hit me now, when I for the first time tried two simple test in parallell or in serial (inband). I have a more elaborate setup with the jest-dev-server like so:

```javascript
  server: {
    command: 'npm run start',
    host: hostname,
    port,
    protocol,
    usedPortAction: 'ignore',
    launchTimeout: 30000,
    waitOnScheme: {
      strictSSL: false,
    },
  },
```

I use the `usedPortAction: 'ignore'` since a user sometimes might have manually started our dev server (via `npm start`) so I've tried to make it work for both scenarios i.e. if it doesn't run it is started.

From @aesyondu last comment it sounds like I'll have to try to use a globalSetup instead where I have something like this https://github.com/smooth-code/jest-puppeteer/tree/master/packages/jest-dev-server#usage - so I will try that in the meantime. I'll report back any findings.

**Comment by aesyondu** [comment]
After adding quite a number of tests, `bin/rails server` couldn't handle the load for the whole test suite. So I went back to using the jest-playwright server config. This way it will restart the server for every test file.

**Comment by thernstig** [comment]
@aesyondu I am not sure I understand that. Why would `bin/rails server`  starting once overload the server?

I've changed my setup to use `globalSetup` and `globalTeardown` like described here https://github.com/smooth-code/jest-puppeteer/tree/master/packages/jest-dev-server#usage. In my case the `command` starts a Node.js express web server, which just handles e2e tests for me. Even if we consider 10 test files/suites running simultaneously that is not overloading the web server in any way, and that number is far more than what is actually run in parallel.

This setup works nicely for me as I start the dev server one, if a user runs the e2e tests locally.

**Comment by aesyondu** [comment]
> @aesyondu I am not sure I understand that. Why would `bin/rails server` starting once overload the server?
> 
> I've changed my setup to use `globalSetup` and `globalTeardown` like described here https://github.com/smooth-code/jest-puppeteer/tree/master/packages/jest-dev-server#usage. In my case the `command` starts a Node.js express web server, which just handles e2e tests for me. Even if we consider 10 test files/suites running simultaneously that is not overloading the web server in any way, and that number is far more than what is actually run in parallel.
> 
> This setup works nicely for me as I start the dev server one, if a user runs the e2e tests locally.

I didn't understand it either. Only now did I realize that I needed to sign_out ALL users before cleaning the database, since the sessions keeps lingering after cleaning the database:

(I have an API exposed for testing only so that I can clean the database using playwright, I took the idea from https://medium.com/@lachlanmiller_52885/e2e-tests-with-cypress-io-and-rails-b652d6ff96db and signing out all users from https://stackoverflow.com/a/14294102/13099902)
```ruby
  def clean_database
    sign_out :user # destroy devise session here
    tables = ActiveRecord::Base.connection.tables
    tables.delete 'schema.migrations'
    tables.each { |t| ActiveRecord::Base.connection.execute("TRUNCATE #{t} CASCADE") }

    render plain: 'Truncated database'
  end
```

**Comment by samuelmaddock** [comment]
The module this one is inspired by, [`jest-puppeteer`](https://github.com/smooth-code/jest-puppeteer), has the desired behavior of setting up the dev server once for all tests.

The code which should be handling this was not implemented in jest-playwright: https://github.com/playwright-community/jest-playwright/blob/570f75b9bac3459398368abb602c8003a5216556/src/global.ts

Instead of setting up the dev server in the jest environment, it should be handled in a [globalSetup](https://jestjs.io/docs/en/configuration#globalsetup-string) and globalTeardown script.
