### ISSUE TITLE
Running in Pipeline "Preset jest-playwright not found."

### ISSUE THREAD

**Issue by sebastianspiller** [playwright-community/jest-playwright#542]
Hello together,

I have an issue concerning Playwright to run in a Continuous Integration Environment (Gitlab Pipeline).

**Describe the bug**
Running on local machine works, running in Gitlab Pipeline breaks with "Validation Error: Preset jest-playwright not found."

**Desktop:**
 - OS: Docker FROM node:12.16.1-slim
 - Playwright version 1.7.0
 - jest-playwright-preset version 1.4.4

**Jest configuration in the `jest.config.js`:**

 ```js
    module.exports = {
        verbose: true,
        'preset': 'jest-playwright-preset',
        'testMatch': ['**/tests/lib/prepareRunningFeatures.js'],
        'setupFiles': [
            './jest-cucumber-config.js',
        ],
        'watchPlugins': [],
        // 'globalSetup': './global-setup.js',
        // 'globalTeardown': './global-teardown.js',
        'testEnvironment': './custom-environment.js',
        'testEnvironmentOptions': {
            'launchOptions': {
                // headless: don't show the browsers' windows, do everything on virtual screens.
                'headless': 'debug' !== process.env.RUN_IN_BROWSER,
                // open devtools in browser
                // NOTE: Set to false if not needed for better performance
                // devtools: false,
                // default window size
            },
            'contextOptions': {
                'viewport': {
                    'width': 1920,
                    'height': 1080,
                },
            },
            'browsers': ['chromium'],
            'devices': [],
        },
    }
```

**Comment by mmarkelov** [comment]
@mxschmitt could you please take a look?

**Comment by mxschmitt** [comment]
Hi @sebastianspiller,
sorry for the late reply, could you share a full example with us?
We have a various amount of examples for different use-cases located [here](https://github.com/playwright-community/playwright-jest-examples). Also since you are using Docker, the [Playwright Docker image](https://playwright.dev/docs/docker) is recommended.

The error itself seems like caused by not installing the [jest-playwright-preset](https://www.npmjs.com/package/jest-playwright-preset) package, but unsure. A small repro would help.

**Comment by mxschmitt** [comment]
Please reopen if the issue is still persistent. Thanks!
