### ISSUE TITLE
Video is not recording anymore after updating to 0.11.1

### ISSUE THREAD

**Issue by kemsky** [playwright-community/jest-playwright#708]
**Describe the bug**
Video folder is empty.

**To Reproduce**
https://github.com/kemsky/playwright-video-bug

**Desktop (please complete the following information):**
<pre>
## System:
 - OS: Windows 10 10.0.19042
 - Memory: 6.74 GB / 31.75 GB
## Binaries:
 - Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
 - npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
## npmPackages:
 - playwright: 1.11.1 => 1.11.1
 - playwright-core: 1.11.1 => 1.11.1

</pre>

**Comment by mxschmitt** [comment]
Was this also reproducible for you in 1.11.0?

**Comment by kemsky** [comment]
@mxschmitt, yes.

**Comment by mmarkelov** [comment]
I'll take a look, but seems like it's related to `playwright`

**Comment by mxschmitt** [comment]
I was able to repro and created an upstream bug: https://github.com/microsoft/playwright/issues/6713

**Comment by mxschmitt** [comment]
Hi, I tried your reproducible, in your case, you had playwright-chromium v1.10 which jest-playwright picked up in the end, thats why saveAs was not defined. Coming to the issue why it was not working, it's because you called saveAs after the super().teardown() was complete, which also closed the whole Playwright process internally. Using this in your teardown works for me:

```js
    async teardown() {
        await Promise.all([
            this.global.page.video().saveAs(`./test.webm`),
            super.teardown()
        ]);
    }
```

**Comment by kemsky** [comment]
@mxschmitt,  the  `Promise.all` does not enforce any order, so it looks really suspicious, but for some reason it works.

The following code with correct order leads to the hanging test:

```
    async teardown() {
        await this.global.page.video().saveAs(`playwright\\videos\\test.webm`);
        await super.teardown();
    }
```

**Comment by mxschmitt** [comment]
It does from my understanding, it calls saveAs, which will block until the context is closed and the super teardown closes the context internally which resolves the saveAs promise.

The reason why recordVideo.dir does not work is because jest-playwright uses launchServer internally, which won't allow that.

**Comment by kemsky** [comment]
@mxschmitt, 

> It does from my understanding, it calls saveAs, which will block until the context is closed and the super teardown closes the context internally which resolves the saveAs promise.

This can be true but does not explain why consecutive awaits do not work and block forever.

Also, the following results in the hanging test as well:
```
        await Promise.all([
            await this.global.page.video().saveAs(`playwright\\videos\\${this.global.expect.getState().currentTestName.replace(/[\s/\\?%*:|"<>]/g, '_')}.webm`),
            super.teardown()
        ]);
```

There is something wrong with locks/blocking etc.

**Comment by mxschmitt** [comment]
Your example will never reach the super.teardown() because saveAs won't resolve until the context was closed, is the code which I provided not working for you? I tried your project and used my code which was working after also updating playwright-chromium to 1.11.

See here, that saveAs waits until the context was closed: https://playwright.dev/docs/api/class-video#videosaveaspath

**Comment by kemsky** [comment]
@mxschmitt, did you try my last example? It looks good exactly like yours, but does some string replacements.

**Comment by mxschmitt** [comment]
The problem in your last example is the await inside the promise.all. If you remove that it should work.
