### ISSUE TITLE
No tracing available in BrowserContext

### ISSUE THREAD

**Issue by mostor-v** [playwright-community/jest-playwright#777]
Hi I'm trying to use trace viewer with jest-playwright but can't start it.

I was trying to start as await context.tracing.start({screenshot:true}) but got an error that property 'traing' doesn't exists under BrowserContext.
Also i was trying to run it like - await (browser as ChromiumBrowser).startTracing(page, {screenshot:true}) but generated tracing is corrupted.

As i see tracing available in playwright\types\BrowserContext but not available in playwright-core\types\BrowserContext which is used by jest-playwright context

jest-playwright = 1.7.0
playwright = 1.13.0

**Comment by mxschmitt** [comment]
startTracing is different from .tracing, see here: https://playwright.dev/docs/api/class-browser#browser-start-tracing

![image](https://user-images.githubusercontent.com/17984549/129396570-2da19610-87dd-488f-a669-37303e6078b6.png)

In your case, its probably because not a recent playwright-core version is used, try to install the latest one via `npm install playwright-core@latest`.

Closing as #746 is a feature request for tracing and its already in the works.

**Comment by mostor-v** [comment]
@mxschmitt i can't understand how i can update playwright-core in separate from jest-playwright?After `npm install playwright-core@latest` my browser context still work with playwright-core from jest-playwright-preset package. I've deleted all node_modules, re-installed all packages 100500 times but still can't use tracing feature.
